name: exchange-rate-app

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    build: ./php-fpm
    depends_on:
      - mysql
      - redis
    networks:
      - app-tier
    volumes:
      - ../backend:/app
    env_file: ../backend/.env

  nginx:
    image: bitnami/nginx:1.29.0
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/server_block.conf:/opt/bitnami/nginx/conf/server_blocks/yourapp.conf:ro
      - ../backend:/app

  mysql:
    image: bitnami/mysql:9.3.0
    networks:
      - app-tier
    volumes:
      - mysql_data:/bitnami/mysql
    env_file: ../backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=Sup3rStron0P4ssw0rd
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  redis:
    image: bitnami/redis:8.0.3
    networks:
      - app-tier
    volumes:
      - redis_data:/bitnami/redis
    env_file: ../backend/.env
    environment:
      - REDIS_PASSWORD=${REDIS_AUTH}

volumes:
  mysql_data:
  redis_data: